config/routes.rb
OpenansCom::Application.routes.draw do
  root :to => 'home#index'  
  resources :qus
  resources :ans
  resources :options
  resources :ques_views
  match "/get-next-qus" => "home#get_next_qus", :as => :get_next_qus
  match "/get-notification/:uid" => "home#get_notification", :as => :get_notification
  match "/how-to-use" => "home#how_to", :as => :how_to
  match "/terms" => "home#terms", :as => :terms
  match "/privacy" => "home#privacy", :as => :privacy
  match "/ask" => "home#ask", :as => :ask
  match "/create-like" => "home#create_like", :as => :create_like
  match "/show-profile" => "home#show_profile", :as => :show_profile
  match "/keep-profile/:id" => "home#keep_profile", :as => :keep_profile
  match "/change-expire-setting/:id" => "home#change_expire", :as => :change_expire
  match "/submit-qu" => "home#submit_qu", :as => :submit_qu
  match "/submit-ans/:id" => "home#submit_ans", :as => :submit_ans
  get 'sitemap.xml', :to => 'home#sitemap', :defaults => { :format => 'xml' }, :conditions => { :method => :get }, :as => :sitemap
  match "/feed/all" => "home#qu_rss", :as => :qu_rss
  match "/search-qu" => "home#search", :as => :search

  match "/trending" => "home#trending", :as => :trending
  match "/latest" => "home#latest", :as => :latest
  match "/most-liked" => "home#most_liked", :as => :most_liked
  match "/most-unliked" => "home#most_unliked", :as => :most_unliked
  match "/unanswered" => "home#unanswered", :as => :unanswered
  match "/activities" => "home#activity", :as => :activity
  match "/contact" => "home#contact", :as => :contact
  match "/stat" => "home#stat", :as => :stat
  match "/how-to-get-notification" => "home#how_notify", :as => :how_notify
  match "/expire-qu/:id" => "qus#expire_qu", :as => :expire_qu
  match "/testing" => "qus#testing", :as => :testing

  match "/:id" => "home#answer", :as => :answer

end

app/models/option.rb
class Option < ActiveRecord::Base
  attr_accessible :content, :qu_id, :seq
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  http_basic_authenticate_with :name => USERNAME, :password => PASSWORD 

  # GET /options
  # GET /options.json
  def index
    @options = Option.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @options }
    end
  end

  # GET /options/1
  # GET /options/1.json
  def show
    @option = Option.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @option }
    end
  end

  # GET /options/new
  # GET /options/new.json
  def new
    @option = Option.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @option }
    end
  end

  # GET /options/1/edit
  def edit
    @option = Option.find(params[:id])
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(params[:option])

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, :notice => 'Option was successfully created.' }
        format.json { render :json => @option, :status => :created, :location => @option }
      else
        format.html { render :action => "new" }
        format.json { render :json => @option.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /options/1
  # PUT /options/1.json
  def update
    @option = Option.find(params[:id])

    respond_to do |format|
      if @option.update_attributes(params[:option])
        format.html { redirect_to @option, :notice => 'Option was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @option.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option = Option.find(params[:id])
    @option.destroy

    respond_to do |format|
      format.html { redirect_to options_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/options/_form.html.erb
<%= form_for(@option) do |f| %>
  <% if @option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
      <% @option.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :qu_id %><br />
    <%= f.text_field :qu_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :seq %><br />
    <%= f.number_field :seq %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/options/edit.html.erb
<h1>Editing option</h1>

<%= render 'form' %>

<%= link_to 'Show', @option %> |
<%= link_to 'Back', options_path %>

app/views/options/index.html.erb
<h1>Listing options</h1>

<table class="table">
  <tr>
    <th>Qu</th>
    <th>Content</th>
    <th>Seq</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @options.each do |option| %>
  <tr>
    <td><%= option.qu_id %></td>
    <td><%= option.content %></td>
    <td><%= option.seq %></td>
    <td><%= link_to 'Show', option %></td>
    <td><%= link_to 'Edit', edit_option_path(option) %></td>
    <td><%= link_to 'Destroy', option, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Option', new_option_path %>

app/views/options/new.html.erb
<h1>New option</h1>

<%= render 'form' %>

<%= link_to 'Back', options_path %>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Qu:</b>
  <%= @option.qu_id %>
</p>

<p>
  <b>Content:</b>
  <%= @option.content %>
</p>

<p>
  <b>Seq:</b>
  <%= @option.seq %>
</p>


<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>