config/routes.rb
OpenansCom::Application.routes.draw do
  root :to => 'home#index'  
  resources :qus
  resources :ans
  resources :options
  resources :ques_views
  match "/get-next-qus" => "home#get_next_qus", :as => :get_next_qus
  match "/get-notification/:uid" => "home#get_notification", :as => :get_notification
  match "/how-to-use" => "home#how_to", :as => :how_to
  match "/terms" => "home#terms", :as => :terms
  match "/privacy" => "home#privacy", :as => :privacy
  match "/ask" => "home#ask", :as => :ask
  match "/create-like" => "home#create_like", :as => :create_like
  match "/show-profile" => "home#show_profile", :as => :show_profile
  match "/keep-profile/:id" => "home#keep_profile", :as => :keep_profile
  match "/change-expire-setting/:id" => "home#change_expire", :as => :change_expire
  match "/submit-qu" => "home#submit_qu", :as => :submit_qu
  match "/submit-ans/:id" => "home#submit_ans", :as => :submit_ans
  get 'sitemap.xml', :to => 'home#sitemap', :defaults => { :format => 'xml' }, :conditions => { :method => :get }, :as => :sitemap
  match "/feed/all" => "home#qu_rss", :as => :qu_rss
  match "/search-qu" => "home#search", :as => :search

  match "/trending" => "home#trending", :as => :trending
  match "/latest" => "home#latest", :as => :latest
  match "/most-liked" => "home#most_liked", :as => :most_liked
  match "/most-unliked" => "home#most_unliked", :as => :most_unliked
  match "/unanswered" => "home#unanswered", :as => :unanswered
  match "/activities" => "home#activity", :as => :activity
  match "/contact" => "home#contact", :as => :contact
  match "/stat" => "home#stat", :as => :stat
  match "/how-to-get-notification" => "home#how_notify", :as => :how_notify
  match "/expire-qu/:id" => "qus#expire_qu", :as => :expire_qu
  match "/testing" => "qus#testing", :as => :testing

  match "/:id" => "home#answer", :as => :answer

end

app/controllers/ques_views_controller.rb
class QuesViewsController < ApplicationController
  http_basic_authenticate_with :name => USERNAME, :password => PASSWORD
  require 'will_paginate/array'
  
  # GET /ques_views
  # GET /ques_views.json
  def index
    if(params[:uid].present?)
      @ques_views = QuesView.find(:all, :conditions => ["uid = ?", params[:uid]], :order => "created_at desc").paginate(:page => params[:page], :per_page => 50)
    else
      @ques_views = QuesView.find(:all, :order => "created_at desc").paginate(:page => params[:page], :per_page => 50)
    end    
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /ques_views/1
  # GET /ques_views/1.json
  def show
    @ques_view = QuesView.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /ques_views/new
  # GET /ques_views/new.json
  def new
    @ques_view = QuesView.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /ques_views/1/edit
  def edit
    @ques_view = QuesView.find(params[:id])
  end

  # POST /ques_views
  # POST /ques_views.json
  def create
    @ques_view = QuesView.new(params[:ques_view])

    respond_to do |format|
      if @ques_view.save
        format.html { redirect_to @ques_view, :notice => 'Ques view was successfully created.' }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /ques_views/1
  # PUT /ques_views/1.json
  def update
    @ques_view = QuesView.find(params[:id])

    respond_to do |format|
      if @ques_view.update_attributes(params[:ques_view])
        format.html { redirect_to @ques_view, :notice => 'Ques view was successfully updated.' }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /ques_views/1
  # DELETE /ques_views/1.json
  def destroy
    @ques_view = QuesView.find(params[:id])
    @ques_view.destroy

    respond_to do |format|
      format.html { redirect_to ques_views_url }
    end
  end
end

app/helpers/ques_views_helper.rb
module QuesViewsHelper
end

app/views/ques_views/_form.html.erb
<%= form_for(@ques_view) do |f| %>
  <% if @ques_view.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ques_view.errors.count, "error") %> prohibited this ques_view from being saved:</h2>

      <ul>
      <% @ques_view.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :qu_id %><br />
    <%= f.number_field :qu_id %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ques_views/edit.html.erb
<h1>Editing ques_view</h1>

<%= render 'form' %>

<%= link_to 'Show', @ques_view %> |
<%= link_to 'Back', ques_views_path %>

app/views/ques_views/index.html.erb
<style>
  body {
  overflow: auto;
  padding: 10px;
  }
  td, th {
  padding: 10px;
  border: 1px solid #ffffff;
  }
  a {
  color: #ffffff;
  text-decoration: none;
  }
</style>
<%= will_paginate @ques_views %>
<table class="table">
  <tr>
    <th>Qu</th>
    <th>Uid</th>
    <th>Count</th>
    <th>ip</th>
    <th>Country</th>
    <th>Region</th>
    <th>City</th>
    <th>When</th>
  </tr>
  <% @ques_views.each do |ques_view| %>
  <tr>
    <td><a href="<%= answer_url(ques_view.qu_id) %>"><%= ques_view.qu_id %><%= %></td>
    <td><a href="<%= ques_views_url(:uid => ques_view.uid) %>"><%= ques_view.uid %></a></td>
    <td><%= ques_view.count %></td>
    <td><%= ques_view.ip %></td>
    <td><%= ques_view.country_name %> - <%= ques_view.country_code %></td>
    <td><%= ques_view.region_name %> - <%= ques_view.region_code %></td>
    <td><%= ques_view.city_name %> - <%= ques_view.latitude %> - <%= ques_view.longitude %></td>
    <td><%= time_ago_in_words(ques_view.created_at) %> ago</td>
  </tr>
<% end %>
</table>
<%= will_paginate @ques_views %>
<br />

app/views/ques_views/new.html.erb
<h1>New ques_view</h1>

<%= render 'form' %>

<%= link_to 'Back', ques_views_path %>

app/views/ques_views/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Qu:</b>
  <%= @ques_view.qu_id %>
</p>

<p>
  <b>Uid:</b>
  <%= @ques_view.uid %>
</p>

<p>
  <b>Count:</b>
  <%= @ques_view.count %>
</p>


<%= link_to 'Edit', edit_ques_view_path(@ques_view) %> |
<%= link_to 'Back', ques_views_path %>