config/routes.rb
OpenansCom::Application.routes.draw do
  root :to => 'home#index'  
  resources :qus
  resources :ans
  resources :options
  resources :ques_views
  match "/get-next-qus" => "home#get_next_qus", :as => :get_next_qus
  match "/get-notification/:uid" => "home#get_notification", :as => :get_notification
  match "/how-to-use" => "home#how_to", :as => :how_to
  match "/terms" => "home#terms", :as => :terms
  match "/privacy" => "home#privacy", :as => :privacy
  match "/ask" => "home#ask", :as => :ask
  match "/create-like" => "home#create_like", :as => :create_like
  match "/show-profile" => "home#show_profile", :as => :show_profile
  match "/keep-profile/:id" => "home#keep_profile", :as => :keep_profile
  match "/change-expire-setting/:id" => "home#change_expire", :as => :change_expire
  match "/submit-qu" => "home#submit_qu", :as => :submit_qu
  match "/submit-ans/:id" => "home#submit_ans", :as => :submit_ans
  get 'sitemap.xml', :to => 'home#sitemap', :defaults => { :format => 'xml' }, :conditions => { :method => :get }, :as => :sitemap
  match "/feed/all" => "home#qu_rss", :as => :qu_rss
  match "/search-qu" => "home#search", :as => :search

  match "/trending" => "home#trending", :as => :trending
  match "/latest" => "home#latest", :as => :latest
  match "/most-liked" => "home#most_liked", :as => :most_liked
  match "/most-unliked" => "home#most_unliked", :as => :most_unliked
  match "/unanswered" => "home#unanswered", :as => :unanswered
  match "/activities" => "home#activity", :as => :activity
  match "/contact" => "home#contact", :as => :contact
  match "/stat" => "home#stat", :as => :stat
  match "/how-to-get-notification" => "home#how_notify", :as => :how_notify
  match "/expire-qu/:id" => "qus#expire_qu", :as => :expire_qu
  match "/testing" => "qus#testing", :as => :testing

  match "/:id" => "home#answer", :as => :answer

end

app/controllers/ans_controller.rb
class AnsController < ApplicationController
  http_basic_authenticate_with :name => USERNAME, :password => PASSWORD
  require 'will_paginate/array'

  # GET /ans
  # GET /ans.json
  def index
    if(params[:uid].present?)
      @ans = Ans.find(:all, :conditions => ["uid = ?", params[:uid]], :order => "created_at desc").paginate(:page => params[:page], :per_page => 50)
    else
      @ans = Ans.find(:all, :order => "created_at desc").paginate(:page => params[:page], :per_page => 50)
    end    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @ans }
    end
  end

  # GET /ans/1
  # GET /ans/1.json
  def show
    @an = Ans.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @an }
    end
  end

  # GET /ans/new
  # GET /ans/new.json
  def new
    @an = Ans.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @an }
    end
  end

  # GET /ans/1/edit
  def edit
    @an = Ans.find(params[:id])
  end

  # POST /ans
  # POST /ans.json
  def create
    @an = Ans.new(params[:an])

    respond_to do |format|
      if @an.save
        format.html { redirect_to @an, :notice => 'Ans was successfully created.' }
        format.json { render :json => @an, :status => :created, :location => @an }
      else
        format.html { render :action => "new" }
        format.json { render :json => @an.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ans/1
  # PUT /ans/1.json
  def update
    @an = Ans.find(params[:id])

    respond_to do |format|
      if @an.update_attributes(params[:an])
        format.html { redirect_to @an, :notice => 'Ans was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @an.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ans/1
  # DELETE /ans/1.json
  def destroy
    @an = Ans.find(params[:id])
    @an.destroy

    respond_to do |format|
      format.html { redirect_to ans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ans_helper.rb
module AnsHelper
end

app/views/ans/_form.html.erb
<%= form_for(@an) do |f| %>
  <% if @an.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@an.errors.count, "error") %> prohibited this an from being saved:</h2>

      <ul>
      <% @an.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_id %><br />
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :req_details %><br />
    <%= f.text_field :req_details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ans/edit.html.erb
<h1>Editing an</h1>

<%= render 'form' %>

<%= link_to 'Show', @an %> |
<%= link_to 'Back', ans_path %>

app/views/ans/index.html.erb
<style>
  body {
  overflow: auto;
  padding: 10px;
  }
  td, th {
  padding: 10px;
  border: 1px solid #ffffff;
  }
  a {
  color: #ffffff;
  text-decoration: none;
  }
</style>
<%= will_paginate @ans %>
<table class="table">
  <tr>
    <th>Uid</th>
    <th>Question</th>
    <th>Value</th>
    <th>Ip</th>
    <th>Country</th>
    <th>Region</th>
    <th>City</th>
    <th>When</th>
    <th></th>
    <th></th>    
  </tr>

<% @ans.each do |an| %>
  <tr>
    <td><a href="<%= ans_url(:uid => an.uid) %>"><%= an.uid %></a></td>
    <td><a href="<%= answer_url(an.question_id) %>"><%= an.question_id %></a></td>
    <td><%= an.value %></td>
    <td><%= an.ip %></td>
    <td><%= an.country_name %> - <%= an.country_code %></td>
    <td><%= an.region_name %> - <%= an.region_code %></td>
    <td><%= an.city_name %> - <%= an.latitude %> - <%= an.longitude %></td>
    <td><%= time_ago_in_words(an.created_at) %></td>
    <td><%= link_to 'Edit', edit_an_path(an) %></td>
    <td><%= link_to 'Destroy', an, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @ans %>
<br />

<%= link_to 'New An', new_an_path %>

app/views/ans/new.html.erb
<h1>New an</h1>

<%= render 'form' %>

<%= link_to 'Back', ans_path %>

app/views/ans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @an.question_id %>
</p>

<p>
  <b>Value:</b>
  <%= @an.value %>
</p>

<p>
  <b>Ip:</b>
  <%= @an.ip %>
</p>

<p>
  <b>Req details:</b>
  <%= @an.req_details %>
</p>


<%= link_to 'Edit', edit_an_path(@an) %> |
<%= link_to 'Back', ans_path %>