config/routes.rb
OpenansCom::Application.routes.draw do
  root :to => 'home#index'  
  resources :qus
  resources :ans
  resources :options
  resources :ques_views
  match "/get-next-qus" => "home#get_next_qus", :as => :get_next_qus
  match "/get-notification/:uid" => "home#get_notification", :as => :get_notification
  match "/how-to-use" => "home#how_to", :as => :how_to
  match "/terms" => "home#terms", :as => :terms
  match "/privacy" => "home#privacy", :as => :privacy
  match "/ask" => "home#ask", :as => :ask
  match "/create-like" => "home#create_like", :as => :create_like
  match "/show-profile" => "home#show_profile", :as => :show_profile
  match "/keep-profile/:id" => "home#keep_profile", :as => :keep_profile
  match "/change-expire-setting/:id" => "home#change_expire", :as => :change_expire
  match "/submit-qu" => "home#submit_qu", :as => :submit_qu
  match "/submit-ans/:id" => "home#submit_ans", :as => :submit_ans
  get 'sitemap.xml', :to => 'home#sitemap', :defaults => { :format => 'xml' }, :conditions => { :method => :get }, :as => :sitemap
  match "/feed/all" => "home#qu_rss", :as => :qu_rss
  match "/search-qu" => "home#search", :as => :search

  match "/trending" => "home#trending", :as => :trending
  match "/latest" => "home#latest", :as => :latest
  match "/most-liked" => "home#most_liked", :as => :most_liked
  match "/most-unliked" => "home#most_unliked", :as => :most_unliked
  match "/unanswered" => "home#unanswered", :as => :unanswered
  match "/activities" => "home#activity", :as => :activity
  match "/contact" => "home#contact", :as => :contact
  match "/stat" => "home#stat", :as => :stat
  match "/how-to-get-notification" => "home#how_notify", :as => :how_notify
  match "/expire-qu/:id" => "qus#expire_qu", :as => :expire_qu
  match "/testing" => "qus#testing", :as => :testing

  match "/:id" => "home#answer", :as => :answer

end

app/models/qu.rb
class Qu < ActiveRecord::Base
  attr_accessible :ans, :likes, :text, :qu_type, :uid, :views, :unlike, :ip, :expire, :expired, :country_code, :country_name, :region_code, :region_name, :city_name, :latitude, :longitude
  
  EXPIRE_6HR = 10
  EXPIRE_DAY = 20
  EXPIRE_WEEK = 30
  EXPIRE_MONTH = 40
  EXPIRE_NEVER = 0

  EXPIRE_TEXT = {  
    EXPIRE_6HR => "Get me answers today, ASAP",
    EXPIRE_DAY => "Get me answers in couple of days",
    EXPIRE_WEEK => "I can wait for this week",
    EXPIRE_MONTH => "It's a difficult one, I will wait for this month",
    EXPIRE_NEVER => "It's a general question, never expire",
  }

  EXPIRED_NO = 0
  EXPIRED_YES = 1  
  EXPIRED_NAMES = {
    EXPIRED_NO => "No",
    EXPIRED_YES => "Yes"
  }

  TYPE_TEXT = 0
  TYPE_SINGLE = 1
  TYPE_NAME = {
    TYPE_TEXT => "Text Based",
    TYPE_SINGLE => "Single Select"
  }

  def self.get_next_question(cur, uid) 
    exc = []
    exc << cur.id if(!cur.nil?)
    if(!uid.nil? && !uid.blank?)
      ans = Ans.find(:all, :conditions => ["uid = ?", uid])
      if(!ans.nil? && !ans.blank?)
        exc = ans.map{|a| a.question_id }
      end
    end    
    exc += QuesView.get_user_views_question(uid)
    if(!exc.nil? && !exc.blank?)
      all_avail_qus = Qu.find(:all, :conditions => ["id not in (?) and expired = ?", exc.uniq, Qu::EXPIRED_NO])
    else
      all_avail_qus = Qu.find(:all, :conditions => ["expired = ?", Qu::EXPIRED_NO], :order => "created_at desc", :limit => 10)
    end
    nxt = ([*all_avail_qus]).sample  
    return nxt
  end
  
  def self.expire_questions(exp_when)
    qus = Qu.find(:all, :conditions => ["expired = ? and expire = ?", Qu::EXPIRED_NO, exp_when])
    for q in qus
      today = Date.today
      cre = q.created_at.to_date
      diff = (today - cre).to_i
      if(q.expire == Qu::EXPIRE_6HR)
        if(diff > 0)
          q.expired = Qu::EXPIRED_YES
          q.save
        end
      elsif(q.expire == Qu::EXPIRE_DAY)
        if(diff > 2)
          q.expired = Qu::EXPIRED_YES
          q.save
        end
      elsif(q.expire == Qu::EXPIRE_WEEK)
        if(diff > 10)
          q.expired = Qu::EXPIRED_YES
          q.save
        end
      elsif(q.expire == EXPIRE_MONTH)
        if(diff > 40)
          q.expired = Qu::EXPIRED_YES
          q.save
        end
      end
    end
  end

  
end

app/controllers/qus_controller.rb
class QusController < ApplicationController
  http_basic_authenticate_with :name => USERNAME, :password => PASSWORD
  require 'will_paginate/array'

  # GET /qus
  # GET /qus.json
  def index
    if(params[:uid].present?)
      @qus = Qu.find(:all, :conditions => ["uid = ?", params[:uid]], :order => "created_at desc").paginate(:page => params[:page], :per_page => 50)
    else
      @qus = Qu.find(:all, :order => "created_at desc").paginate(:page => params[:page], :per_page => 50)
    end    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @qus }
    end
  end

  # GET /qus/1
  # GET /qus/1.json
  def show
    @qu = Qu.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @qu }
    end
  end

  # GET /qus/new
  # GET /qus/new.json
  def new
    @qu = Qu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @qu }
    end
  end

  # GET /qus/1/edit
  def edit
    @qu = Qu.find(params[:id])
  end

  # POST /qus
  # POST /qus.json
  def create
    @qu = Qu.new(params[:qu])

    respond_to do |format|
      if @qu.save
        format.html { redirect_to @qu, :notice => 'Qu was successfully created.' }
        format.json { render :json => @qu, :status => :created, :location => @qu }
      else
        format.html { render :action => "new" }
        format.json { render :json => @qu.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /qus/1
  # PUT /qus/1.json
  def update
    @qu = Qu.find(params[:id])
    respond_to do |format|
      if @qu.update_attributes(params[:qu])
        format.html { redirect_to @qu, :notice => 'Qu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @qu.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /qus/1
  # DELETE /qus/1.json
  def destroy
    @qu = Qu.find(params[:id])
    @qu.destroy
    respond_to do |format|
      format.html { redirect_to qus_url }
      format.json { head :no_content }
    end
  end

  def expire_qu
    qu = Qu.find(params[:id])
    qu.expired = (qu.expired == Qu::EXPIRED_YES)? Qu::EXPIRED_NO : Qu::EXPIRED_YES
    qu.save
    render(:text => Qu::EXPIRED_NAMES[qu.expired])
  end

  def testing
    qus = Qu.all
    for q in qus
      q.expire = 0
      q.expired = 0
      q.save
    end
    render(:text => "Im success")
  end
end

app/helpers/qus_helper.rb
module QusHelper
end

app/views/qus/_form.html.erb
<%= form_for(@qu) do |f| %>
  <% if @qu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qu.errors.count, "error") %> prohibited this qu from being saved:</h2>

      <ul>
      <% @qu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uid %><br />
    <%= f.number_field :uid %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :qu_type %><br />
    <%= f.number_field :qu_type %>
  </div>
  <div class="field">
    <%= f.label :views %><br />
    <%= f.number_field :views %>
  </div>
  <div class="field">
    <%= f.label :like %><br />
    <%= f.number_field :like %>
  </div>
  <div class="field">
    <%= f.label :ans %><br />
    <%= f.number_field :ans %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qus/edit.html.erb
<h1>Editing qu</h1>

<%= render 'form' %>

<%= link_to 'Show', @qu %> |
<%= link_to 'Back', qus_path %>

app/views/qus/index.html.erb
<style>
  body {
  padding: 10px;
  overflow: auto;
  }
  td, th {
  padding: 10px;
  border: 1px solid #ffffff;
  }
  a {
  color: #ffffff;
  text-decoration: none;
  }
</style>
<%= will_paginate @qus %>
<table class="table">
  <tr>
    <th>Uid</th>
    <th>Text</th>
    <th>Type</th>
    <th>Views</th>
    <th>Likes</th>
    <th>Unlikes</th>
    <th>Ans</th>
    <th>Expire</th>
    <th>Expired</th>
    <th>ip</th>
    <th>Country</th>
    <th>Region</th>
    <th>City</th>
    <th>When</th>
    <th>Tags</th>
    <th></th>
    <th></th>
  </tr>

  <%
     extractor = Phrasie::Extractor.new
     @qus.each do |qu|
     tags = extractor.phrases(qu.text, :strength => 2, :occur => 1)
  %>
  <tr>
    <td><a href="<%= qus_url(:uid => qu.uid) %>"><%= qu.uid %></a></td>
    <td><a href="<%= answer_url(qu.id) %>"><%= qu.text %></a></td>
    <td><%= Qu::TYPE_NAME[qu.qu_type] %></td>
    <td><%= qu.views %></td>
    <td><%= qu.like %></td>
    <td><%= qu.unlike %></td>
    <td><%= qu.ans %></td>
    <td><%= Qu::EXPIRE_TEXT[qu.expire] %></td>
    <td><a target="_blank" href="<%= expire_qu_url(qu.id) %>"><%= Qu::EXPIRED_NAMES[qu.expired] %></a></td>
    <td><%= qu.ip %></td>
    <td><%= qu.country_name %> - <%= qu.country_code %></td>
    <td><%= qu.region_name %> - <%= qu.region_code %></td>
    <td><%= qu.city_name %> - <%= qu.latitude %> - <%= qu.longitude %></td>
    <td><%= time_ago_in_words(qu.created_at) %></td>
    <td><%=raw tags.map{|a| a.first }.join("<br><br>") %></td>
    <td><%= link_to 'Edit', edit_qu_path(qu) %></td>
    <td><%= link_to 'Destroy', qu, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @qus %>
<br />

<%= link_to 'New Qu', new_qu_path %>

app/views/qus/new.html.erb
<h1>New qu</h1>

<%= render 'form' %>

<%= link_to 'Back', qus_path %>

app/views/qus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uid:</b>
  <%= @qu.uid %>
</p>

<p>
  <b>Text:</b>
  <%= @qu.text %>
</p>

<p>
  <b>Type:</b>
  <%= @qu.type %>
</p>

<p>
  <b>Views:</b>
  <%= @qu.views %>
</p>

<p>
  <b>Likes:</b>
  <%= @qu.likes %>
</p>

<p>
  <b>Ans:</b>
  <%= @qu.ans %>
</p>


<%= link_to 'Edit', edit_qu_path(@qu) %> |
<%= link_to 'Back', qus_path %>